Flagroom5_1_MapScripts::
	.byte 0


Flagroom5_1_Logbook1::
    msgbox Flagroom5_1_Text_Logbook1, MSGBOX_DEFAULT
    release
    end



Flagroom5_1_Text_Logbook1::
	.string "Entry in the captain's logbook:\n"
	.string "Keeping logbooks is an important\p"
	.string "matter. Often, it is only in the\n"
	.string "logbooks that you can see what you\p"
	.string "have actually accomplished. But it\n"
	.string "can also open your eyes and give\p"
	.string "you ideas for new adventures. I\n"
	.string "will never underestimate logbooks\p"
	.string "again.$"

